### ISSUE TITLE
KeyError: 'Cannot detect if using keras or tf.keras.'

### ISSUE THREAD

**Issue by changbaishan** [mnicnc404/CartoonGan-tensorflow#15]
Following your instruction, I have performed this:
git clone https://www.github.com/keras-team/keras-contrib.git \
    && cd keras-contrib \
    && python convert_to_tf_keras.py \
    && USE_TF_KERAS=1 python setup.py install

But when I tested this:
python cartoonize.py --input_dir input_images --output_dir output_images --styles shinkai hayao --comparison_view horizontal 

The following error error happened:
Traceback (most recent call last):
  File "cartoonize.py", line 11, in <module>
    from style_transfer.cartoongan import cartoongan
  File "/home/myself/Documents/sandbox/playground/testtwo/CartoonGan-tensorflow/style_transfer/cartoongan/cartoongan.py", line 4, in <module>
    from keras_contrib.layers import InstanceNormalization
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/myself/anaconda3/envs/cartoongan/lib/python3.6/site-packages/keras_contrib-2.0.8-py3.6.egg/keras_contrib/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/myself/anaconda3/envs/cartoongan/lib/python3.6/site-packages/keras_contrib-2.0.8-py3.6.egg/keras_contrib/layers/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/myself/anaconda3/envs/cartoongan/lib/python3.6/site-packages/keras_contrib-2.0.8-py3.6.egg/keras_contrib/layers/advanced_activations/pelu.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/myself/anaconda3/envs/cartoongan/lib/python3.6/site-packages/keras_contrib-2.0.8-py3.6.egg/keras_contrib/utils/test_utils.py", line 188, in <module>
KeyError: 'Cannot detect if using keras or tf.keras.'

Can you please help? Thanks very much.

**Comment by Govan111** [comment]
Have you solve this problem?

**Comment by changbaishan** [comment]
Not yet. Right now I work on something else. Do you have any idea how I can try?

Thanks very much!

**Comment by leemengtaiwan** [comment]
@changbaishan Make sure you follow **every** install commands specified in our [demo Colab notebook](https://colab.research.google.com/drive/1WIZBHix_cYIGsBKa4phIwCq5qXwO8fRX) including the correct TensorFlow version.

I just confirmed that the Colab notebook worked perfectly well, so you should be able to solve the issue by just following it.

If even the notebook is not working, we can reopen the issue.

**Comment by mnicnc404** [comment]
> Following your instruction...

Can you provide the instruction that you used to build your environment, along with your OS?

**Comment by Aacrobat** [comment]
i meet the same qusetion; when i open the source code i installed, i found that it is not match to the webside:
"""Utilities related to Keras unit tests."""
import sys
import numpy as np
from numpy.testing import assert_allclose
import inspect

import keras
from keras.layers import Input
from keras.models import Model
from keras import backend as K

i do not know what's wrong with the git and install code

**Comment by iszotic** [comment]
You could try using using tensorflow addons layers, instead of 
`from keras_contrib.layers import InstanceNormalization` use 
`from tfa.normalizations import InstanceNormalization`
That did the trick for me

**Comment by CodTan** [comment]
@iszotic I am facing the same problem as in the issue and then, tried doing what worked for you. Could you please let me  know your Python version? 
I am working with Python 3.7.5 and am unable to install `tensorflow-addons`.

**Comment by CodTan** [comment]
I was facing the same issue; found out that I installed `tensorflow-gpu==2.0.0` instead of `tensorflow-gpu==2.0.0-alpha0`. Installing the latter fixed the issue.

**Comment by mumtozvalijonov** [comment]
Solved. Try running cconvert_to_tf_keras.py from the directory where train.py is located. 
`cd directory/where/train_py_is_located`
`python directory/where/convert_to_tf_keras_py_located/convert_to_tf_keras.py`
This should convert all keras calls to tf.keras calls and solve the issue.
