### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'get_default_graph

### ISSUE THREAD

**Issue by WenheLI** [mnicnc404/CartoonGan-tensorflow#17]
Thanks for your excellent work!
I got an error of `AttributeError: module 'tensorflow' has no attribute 'get_default_graph` when I try to run your code. It seems to be a dependency issue do you have any clue?

**Comment by HuangDanGeeker** [comment]
I wander if you @WenheLI  ever have dealed with this problem 'ImportError: cannot import name 'export_saved_model'

**Comment by mnicnc404** [comment]
> Thanks for your excellent work!
> I got an error of `AttributeError: module 'tensorflow' has no attribute 'get_default_graph` when I try to run your code. It seems to be a dependency issue do you have any clue?

Can you kindly provide the commands resulting in the error?

**Comment by JOJO-JAVA** [comment]
[2020-07-02 16:19:32] [Trainer] [INFO] Initializing generator with batch_size: 4, input_size: 256...
Traceback (most recent call last):
  File "train.py", line 696, in <module>
    main(**kwargs)
  File "train.py", line 632, in main
    t.pretrain_generator()
  File "train.py", line 337, in pretrain_generator
    generator = Generator(base_filters=2 if self.debug else 64, light=self.light)
  File "/root/CartoonGan-tensorflow-master/generator.py", line 29, in __init__
    pad_type=pad_type)
  File "/root/CartoonGan-tensorflow-master/layers.py", line 66, in __init__
    self.model.add(get_norm(norm_type))
  File "/root/CartoonGan-tensorflow-master/layers.py", line 46, in get_norm
    return InstanceNormalization()
  File "/root/anaconda3/lib/python3.6/site-packages/keras_contrib-2.0.8-py3.6.egg/keras_contrib/layers/normalization/instancenormalization.py", line 62, in __init__
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 132, in __init__
    name = _to_snake_case(prefix) + '_' + str(K.get_uid(prefix))
  File "/root/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 74, in get_uid
    graph = tf.get_default_graph()

**Comment by JOJO-JAVA** [comment]
@mnicnc404 

[2020-07-02 16:19:32] [Trainer] [INFO] Initializing generator with batch_size: 4, input_size: 256...
Traceback (most recent call last):
File "train.py", line 696, in 
main(**kwargs)
File "train.py", line 632, in main
t.pretrain_generator()
File "train.py", line 337, in pretrain_generator
generator = Generator(base_filters=2 if self.debug else 64, light=self.light)
File "/root/CartoonGan-tensorflow-master/generator.py", line 29, in init
pad_type=pad_type)
File "/root/CartoonGan-tensorflow-master/layers.py", line 66, in init
self.model.add(get_norm(norm_type))
File "/root/CartoonGan-tensorflow-master/layers.py", line 46, in get_norm
return InstanceNormalization()
File "/root/anaconda3/lib/python3.6/site-packages/keras_contrib-2.0.8-py3.6.egg/keras_contrib/layers/normalization/instancenormalization.py", line 62, in init
File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 132, in init
name = to_snake_case(prefix) + '' + str(K.get_uid(prefix))
File "/root/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 74, in get_uid
graph = tf.get_default_graph()

**Comment by JOJO-JAVA** [comment]
> > Thanks for your excellent work!
> > I got an error of `AttributeError: module 'tensorflow' has no attribute 'get_default_graph` when I try to run your code. It seems to be a dependency issue do you have any clue?
> 
> Can you kindly provide the commands resulting in the error?

[2020-07-02 16:19:32] [Trainer] [INFO] Initializing generator with batch_size: 4, input_size: 256...
Traceback (most recent call last):
File "train.py", line 696, in
main(**kwargs)
File "train.py", line 632, in main
t.pretrain_generator()
File "train.py", line 337, in pretrain_generator
generator = Generator(base_filters=2 if self.debug else 64, light=self.light)
File "/root/CartoonGan-tensorflow-master/generator.py", line 29, in init
pad_type=pad_type)
File "/root/CartoonGan-tensorflow-master/layers.py", line 66, in init
self.model.add(get_norm(norm_type))
File "/root/CartoonGan-tensorflow-master/layers.py", line 46, in get_norm
return InstanceNormalization()
File "/root/anaconda3/lib/python3.6/site-packages/keras_contrib-2.0.8-py3.6.egg/keras_contrib/layers/normalization/instancenormalization.py", line 62, in init
File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 132, in init
name = to_snake_case(prefix) + '' + str(K.get_uid(prefix))
File "/root/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 74, in get_uid
graph = tf.get_default_graph()
