### ISSUE TITLE
Error running train.py

### ISSUE THREAD

**Issue by menu23** [mnicnc404/CartoonGan-tensorflow#19]
I tried running train.py using the parameters suggested for <16GB.
This is the stack trace I got.

Traceback (most recent call last):
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 8, in <module>
    import tensorflow as tf
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/__init__.py", line 27, in <module>
    from tensorflow._api.v2 import audio
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/_api/v2/audio/__init__.py", line 8, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/wbet/anaconda3/envs/cartoongan/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by giuliacern** [comment]
I've got the same error, why have you closed the issue?

**Comment by giuliacern** [comment]
I solved installing cudatoolkit=10.0 from anaconda
