### ISSUE TITLE
The added layer must be an instance of class Layer

### ISSUE THREAD

**Issue by 360disrupt** [mnicnc404/CartoonGan-tensorflow#22]
If I run this command:
```
python train.py     --batch_size 4     --pretrain_epochs 1     --content_lambda .4     --pretrain_learning_rate 1e-4     --g_adv_lambda 8.     --generator_lr 4e-5     --discriminator_lr 1.5e-5     --style_lambda 25.     --light     --dataset_name mozart
```

I run into this err.
```
user:CartoonGan-tensorflow user$ python train.py     --batch_size 4     --pretrain_epochs 1     --content_lambda .4     --pretrain_learning_rate 1e-4     --g_adv_lambda 8.     --generator_lr 4e-5     --discriminator_lr 1.5e-5     --style_lambda 25.     --light     --dataset_name mozart
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
Using TensorFlow backend.
[2019-09-27 15:34:29] [Trainer] [INFO] Setting up VGG19 for computing content loss...
[2019-09-27 15:34:30] [Trainer] [INFO] Setting up objective functions and metrics using lsgan...
[2019-09-27 15:34:30] [Trainer] [INFO] Setting up checkpoint paths...
[2019-09-27 15:34:30] [Trainer] [INFO] Starting to pretrain generator with 1 epochs...
[2019-09-27 15:34:30] [Trainer] [INFO] Building `mozart` dataset with domain `A`...
[2019-09-27 15:34:30] [Trainer] [INFO] Found 5 domainA images in trainA folder.
WARNING:tensorflow:From train.py:221: shuffle_and_repeat (from tensorflow.python.data.experimental.ops.shuffle_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.shuffle(buffer_size, seed)` followed by `tf.data.Dataset.repeat(count)`. Static tf.data optimizations will take care of using the fused implementation.
WARNING:tensorflow:From train.py:221: shuffle_and_repeat (from tensorflow.python.data.experimental.ops.shuffle_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.shuffle(buffer_size, seed)` followed by `tf.data.Dataset.repeat(count)`. Static tf.data optimizations will take care of using the fused implementation.
WARNING:tensorflow:From train.py:229: map_and_batch (from tensorflow.python.data.experimental.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map(map_func, num_parallel_calls)` followed by `tf.data.Dataset.batch(batch_size, drop_remainder)`. Static tf.data optimizations will take care of using the fused implementation.
WARNING:tensorflow:From train.py:229: map_and_batch (from tensorflow.python.data.experimental.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map(map_func, num_parallel_calls)` followed by `tf.data.Dataset.batch(batch_size, drop_remainder)`. Static tf.data optimizations will take care of using the fused implementation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:tensorflow:Entity <function Trainer.get_dataset.<locals>.fn at 0x10e6d31e0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <function Trainer.get_dataset.<locals>.fn at 0x10e6d31e0> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: Bad argument number for Name: 3, expecting 4
WARNING:tensorflow:Entity <bound method Trainer.image_processing of <tensorflow.python.eager.function.TfMethodTarget object at 0x139e667b8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
WARNING:tensorflow:Entity <bound method Trainer.image_processing of <tensorflow.python.eager.function.TfMethodTarget object at 0x139e667b8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
[2019-09-27 15:34:30] [Trainer] [INFO] Initializing generator with batch_size: 4, input_size: 256...
Traceback (most recent call last):
  File "train.py", line 696, in <module>
    main(**kwargs)
  File "train.py", line 632, in main
    t.pretrain_generator()
  File "train.py", line 337, in pretrain_generator
    generator = Generator(base_filters=2 if self.debug else 64, light=self.light)
  File "/Users/user/Projekte/1-NODEJS/image-ai/CartoonGan-tensorflow/generator.py", line 29, in __init__
    pad_type=pad_type)
  File "/Users/user/Projekte/1-NODEJS/image-ai/CartoonGan-tensorflow/layers.py", line 66, in __init__
    self.model.add(get_norm(norm_type))
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 158, in add
    'Found: ' + str(layer))
TypeError: The added layer must be an instance of class Layer. Found: <keras_contrib.layers.normalization.instancenormalization.InstanceNormalization object at 0x10e6e6278>
user:CartoonGan-tensorflow user$ 

```

Are the images required to have the same sizes/ get they auto cropped?

`python --version: Python 3.6.5`

**Comment by 360disrupt** [comment]
Reinstalled everything works now.

**Comment by amshetty** [comment]
I am running into the same problem. Could please elaborate on what packages you have reinstalled?
