### ISSUE TITLE
Error in tf_keras_contrib

### ISSUE THREAD

**Issue by ElegantLin** [mnicnc404/CartoonGan-tensorflow#35]
```
>>> from keras_contrib.layers import InstanceNormalization
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/dzl-local/miniconda3/envs/cartoon/lib/python3.6/site-packages/tf_keras_contrib-2.0.8-py3.6.egg/keras_contrib/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/dzl-local/miniconda3/envs/cartoon/lib/python3.6/site-packages/tf_keras_contrib-2.0.8-py3.6.egg/keras_contrib/layers/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/dzl-local/miniconda3/envs/cartoon/lib/python3.6/site-packages/tf_keras_contrib-2.0.8-py3.6.egg/keras_contrib/layers/advanced_activations/pelu.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
  File "/home/dzl-local/miniconda3/envs/cartoon/lib/python3.6/site-packages/tf_keras_contrib-2.0.8-py3.6.egg/keras_contrib/utils/test_utils.py", line 7
    from tensorflow from tensorflow from tensorflow import keras
                       ^
SyntaxError: invalid syntax
```

I followed the following instructions
```
git clone https://www.github.com/keras-team/keras-contrib.git \
    && cd keras-contrib \
    && python convert_to_tf_keras.py \
    && USE_TF_KERAS=1 python setup.py install
```

Did anyone meet this problem? Thanks!

**Comment by iwanttobeabigone** [comment]
Hello, I think I should know about this issue. I read a blog post about it, and you read the last sentence in your log: "from tensorflow from tensorflow from tensorflow import keras", you should be executing The python convert_to_tf_keras.py command many times has caused many prefixes in front of your tensorflow, so the solution I proposed is:
1. Delete your tf_keras_contrib-2.0.8-py3.6.egg file (this file is the thing that you execute the setup.py file installation, mine is C: \ Users \ 90496 \ Anaconda3 \ installed in this directory envs \ tensorflow \ Lib \ site-packages), and be sure to delete the easyinstall.pth file at the same time
2. Re-run your above command, that is, enter the keras-contrib directory and run the following two commands python convert_to_tf_keras.py \ && USE_TF_KERAS = 1 python setup.py install
Hope that can help you.

**Comment by ElegantLin** [comment]
Hi, @iwanttobeabigone. Thanks for your answer. I am puzzled your statement
`be sure to delete the easyinstall.pth file at the same time`. 
I have deleted `tf_keras_contrib-2.0.8-py3.6.egg` and re-run step 2 (I did not re-clone the keras-contrib. Should I re-clone again?). I re-run the code and I got the following error message
```
Traceback (most recent call last):
  File "cartoonize.py", line 11, in <module>
    from style_transfer.cartoongan import cartoongan
  File "/home/432/dzl/CartoonGan-tensorflow/style_transfer/cartoongan/cartoongan.py", line 4, in <module>
    from keras_contrib.layers import InstanceNormalization
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/dzl-local/miniconda3/envs/cartoon/lib/python3.6/site-packages/tf_keras_contrib-2.0.8-py3.6.egg/keras_contrib/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/dzl-local/miniconda3/envs/cartoon/lib/python3.6/site-packages/tf_keras_contrib-2.0.8-py3.6.egg/keras_contrib/layers/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/dzl-local/miniconda3/envs/cartoon/lib/python3.6/site-packages/tf_keras_contrib-2.0.8-py3.6.egg/keras_contrib/layers/advanced_activations/pelu.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
  File "/home/dzl-local/miniconda3/envs/cartoon/lib/python3.6/site-packages/tf_keras_contrib-2.0.8-py3.6.egg/keras_contrib/utils/test_utils.py", line 7
    from tensorflow from tensorflow from tensorflow from tensorflow from tensorflow from tensorflow import keras
                       ^
SyntaxError: invalid syntax
```

I am really puzzled about this !!!??? Could you please help me with this (QAQ)?

**Comment by iwanttobeabigone** [comment]
I'm sorry the steps I said last time are incomplete, the solution:
1. delete the keras-contrib file you downloaded from github
2. Delete the tf_keras_contrib-2.0.8-py3.6.egg file, and delete the easyinstall.pth file
3. Now come over the previous command (convert_to_tf_keras.py here can only be run once, the result of the operation should be modified in 73 places):
git clone https://www.github.com/keras-team/keras-contrib.git \
     && cd keras-contrib \
     && python convert_to_tf_keras.py \
     && USE_TF_KERAS = 1 python setup.py install
You can take a look at the reference blog: http://blog.sina.com.cn/s/blog_a99f842a0102yot5.html

**Comment by ElegantLin** [comment]
Hi, thanks for your previous post. I have solved the problem and run it successfully :-).
