### ISSUE TITLE
Error :  Sequential model should have unique names

### ISSUE THREAD

**Issue by pradyumnjain** [mnicnc404/CartoonGan-tensorflow#49]
Here is the traceback of the error I got

Traceback (most recent call last):
  File "train.py", line 696, in <module>
    main(**kwargs)
  File "train.py", line 632, in main
    t.pretrain_generator()
  File "train.py", line 337, in pretrain_generator
    generator = Generator(base_filters=2 if self.debug else 64, light=self.light)
  File "/home/akshit/pradyumn/cartoonize/CartoonGan-tensorflow/generator.py", line 45, in __init__
    kernel_size=3) for _ in range(num_resblocks)])
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 517, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 144, in __init__
    self.add(layer)
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 517, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 191, in add
    'to pass a unique name.' % (layer.name,))
ValueError: All layers added to a Sequential model should have unique names. Name "BasicShuffleUnitV2" is already the name of a layer in this model. Update the `name` argument to pass a unique name.

**Comment by Alanways** [comment]
I changed line 82 in "layers.py" to "super(BasicShuffleUnitV2, self).__init__()", just deleted the name parameter, and this is solved

**Comment by pradyumnjain** [comment]
> I changed line 82 in "layers.py" to "super(BasicShuffleUnitV2, self).**init**()", just deleted the name parameter, and this is solved

Yes, this worked thanks.
