### ISSUE TITLE
Incompatible Shape error

### ISSUE THREAD

**Issue by pradyumnjain** [mnicnc404/CartoonGan-tensorflow#52]
Traceback (most recent call last):
  File "train.py", line 696, in <module>
    main(**kwargs)
  File "train.py", line 632, in main
    t.pretrain_generator()
  File "train.py", line 352, in pretrain_generator
    os.path.join(self.checkpoint_dir, "pretrain")))
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.6/site-packages/tensorflow/python/training/tracking/util.py", line 1470, in restore
    status = self._saver.restore(save_path=save_path)
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.6/site-packages/tensorflow/python/training/tracking/util.py", line 1096, in restore
    self._graph_view.root)
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 209, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 779, in _restore_from_checkpoint_position
    visit_queue=visit_queue)))
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 791, in _single_restoration_from_checkpoint_position
    restore_ops = checkpoint_position.restore_ops()
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 393, in restore_ops
    tensor_saveables, python_saveables))
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.6/site-packages/tensorflow/python/training/tracking/util.py", line 162, in restore_saveables
    self.save_path_tensor, validated_saveables)
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.6/site-packages/tensorflow/python/training/saving/functional_saver.py", line 137, in restore_from_saveable_objects
    restored_shapes=None))
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.6/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 115, in restore
    self.handle_op, self._var_shape, restored_tensor)
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.6/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 272, in shape_safe_assign_variable_handle
    shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/akshit/anaconda3/envs/cartoongan/lib/python3.6/site-packages/tensorflow/python/framework/tensor_shape.py", line 1072, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (7, 7, 64, 3) and (5, 5, 96, 3) are incompatible
``

I wonder if it's because of variable size input data. What are the constraints for trainA and trainB anyway?

**Comment by pradyumnjain** [comment]
Solved it by running the smooth.py script again
